on: [push, pull_request]
name: build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./internal/... ./cmd/...
      if: runner.os != 'Linux'
    - name: Test with coverage
      run: go test -cover -race -coverprofile=coverage.txt -covermode=atomic ./internal/... ./cmd/...
      if: runner.os == 'Linux'
    - name: Upload coverage data to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
      if: runner.os == 'Linux'
